# Generated by Django 5.2.7 on 2025-11-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="planned_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
