# Generated by Django 5.2.7 on 2025-11-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_tasknote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="description",
        ),
    ]
