# Generated by Django 5.2.7 on 2026-05-03 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_seed_space_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="repeat_generated_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="repeat_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repeat_instances",
                to="core.task",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="repeat_series_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
