# Generated by Django 5.2.7 on 2026-05-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_task_repeat_generated_until_task_repeat_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="estimated_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (10, "10 mins"),
                    (30, "30 mins"),
                    (60, "1 hour"),
                    (120, "2 hours"),
                    (240, "4 hours"),
                    (360, "6 hours"),
                    (361, "+6 hours"),
                ],
                null=True,
            ),
        ),
    ]
