# Generated by Django 5.2.7 on 2026-06-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journeys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermission",
            name="seen",
            field=models.BooleanField(default=False),
        ),
    ]
