# Generated by Django 5.2.7 on 2026-06-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journeys", "0002_usermission_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="is_required",
            field=models.BooleanField(default=True),
        ),
    ]
