# Generated by Django 5.2.7 on 2026-06-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journeys", "0003_mission_is_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="guidance_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="guidance_tip",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mission",
            name="guidance_title",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
