# Generated by Django 5.2.7 on 2026-06-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journeys", "0004_mission_guidance_text_mission_guidance_tip_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="video_title",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="mission",
            name="video_url",
            field=models.URLField(blank=True),
        ),
    ]
