# Generated by Django 5.2.7 on 2026-06-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journeys", "0005_mission_video_title_mission_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="badge_image",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
