# Generated by Django 5.2.7 on 2026-06-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journeys", "0006_achievement_badge_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="mission_videos/"),
        ),
    ]
