# Generated by Django 5.2.7 on 2026-07-17 14:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_seed_plans_and_memberships"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="grace_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="last_successful_payment_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("merchant_payment_id", models.CharField(max_length=64, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("currency", models.CharField(default="ZAR", max_length=3)),
                ("environment", models.CharField(default="sandbox", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("submitted", "Submitted"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_attempts",
                        to="subscriptions.plan",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_attempts",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dedupe_key", models.CharField(max_length=64, unique=True)),
                (
                    "provider_payment_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "merchant_payment_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("payment_status", models.CharField(blank=True, max_length=30)),
                ("sanitized_payload", models.JSONField(default=dict)),
                ("payload_hash", models.CharField(max_length=64)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("signature_valid", models.BooleanField(default=False)),
                ("source_valid", models.BooleanField(default=False)),
                ("provider_validation_valid", models.BooleanField(default=False)),
                ("validation_error", models.CharField(blank=True, max_length=255)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="subscriptions.paymentattempt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="payfast", max_length=20)),
                ("provider_payment_id", models.CharField(max_length=255, unique=True)),
                ("merchant_payment_id", models.CharField(db_index=True, max_length=64)),
                (
                    "provider_subscription_token",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("initial", "Initial"), ("renewal", "Renewal")],
                        default="initial",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "fee_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("currency", models.CharField(default="ZAR", max_length=3)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="subscriptions.paymentattempt",
                    ),
                ),
                (
                    "notification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transaction",
                        to="subscriptions.paymentnotification",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_transactions",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
        ),
    ]
