"""
Django settings for finy project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


SECRET_KEY = config("SECRET_KEY")
DEBUG = config("DEBUG", default=False, cast=bool)

RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")

ALLOWED_HOSTS = ["127.0.0.1", "localhost", "finy.co.za", "www.finy.co.za", "41.61.20.230"]


if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

ALLOWED_HOSTS += [
    "finy.co.za",
    "www.finy.co.za",
]


# Application definition

INSTALLED_APPS = [
    # Django built-ins
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party

    # Local apps
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'core',
    'api',
    'ui',
    'journeys',
    'subscriptions',
]

if DEBUG:
    RATELIMIT_IP_META_KEY = "REMOTE_ADDR"
else:
    RATELIMIT_IP_META_KEY = "HTTP_X_FORWARDED_FOR"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "finy.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "finy.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

AUTHENTICATION_BACKENDS = [
    "ui.auth_backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.console.EmailBackend"
)


EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=False, cast=bool)


DEFAULT_FROM_EMAIL = config(
    "DEFAULT_FROM_EMAIL",
    default="no-reply@finy.co.za"
)

ADMIN_NOTIFICATION_EMAIL = config(
    "ADMIN_NOTIFICATION_EMAIL",
    default="mbasa.dinga@gmail.com"
)





# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Johannesburg'  # Set to South Africa's time zone

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

TEMPLATES[0]["DIRS"] = [BASE_DIR / "templates"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# PayFast Stage 1 is deliberately sandbox-only. Secrets must be supplied through
# environment variables and are never stored in the database.
PAYFAST_ENABLED = config("PAYFAST_ENABLED", default=False, cast=bool)
PAYFAST_ENVIRONMENT = config("PAYFAST_ENVIRONMENT", default="sandbox")
PAYFAST_MERCHANT_ID = config("PAYFAST_MERCHANT_ID", default="")
PAYFAST_MERCHANT_KEY = config("PAYFAST_MERCHANT_KEY", default="")
PAYFAST_PASSPHRASE = config("PAYFAST_PASSPHRASE", default="")
FINY_PUBLIC_BASE_URL = config("FINY_PUBLIC_BASE_URL", default="http://localhost:8000")
PAYFAST_HTTP_TIMEOUT_SECONDS = config("PAYFAST_HTTP_TIMEOUT_SECONDS", default=10, cast=int)
PAYFAST_API_VERSION = config("PAYFAST_API_VERSION", default="v1")
PAYFAST_TRUSTED_PROXIES = config("PAYFAST_TRUSTED_PROXIES", default="")
PAYFAST_SOURCE_HOSTS = config(
    "PAYFAST_SOURCE_HOSTS",
    default="sandbox.payfast.co.za,www.payfast.co.za,w1w.payfast.co.za,w2w.payfast.co.za",
)


# DRF (basic)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}
